logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: DEBUG
server:
  port: 8088
spring:
  datasource:
    url:  jdbc:h2:file:./h2/org2
  jpa:
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true
  flyway:
    enabled: true